# GitBook Configuration
root: ./

# Structure
structure:
  readme: README.md
  summary: SUMMARY.md

# Git integration
git:
  branch: main

# Plugins
plugins:
  - search-plus
  - sharing
  - fontsettings
  
# PDF options
pdf:
  pageNumbers: true
  fontSize: 12
  fontFamily: "Arial"
  paperSize: a4
  margin:
    right: 62
    left: 62
    top: 56
    bottom: 56