name: _REMOVED_ Auto-fix Markdown (Replaced by autofix.ci)
# Original logic migrated to autofix-ci.yml.
on:
	workflow_call:
jobs:
	noop:
		if: false
		runs-on: ubuntu-latest
		steps:
			- run: echo "Deprecated workflow placeholder"