name: _REMOVED_ Markdown Lint (Do not use)
# This file intentionally left minimal; original workflow replaced by docs-quality.yml
on:
	workflow_call:
jobs:
	noop:
		if: false
		runs-on: ubuntu-latest
		steps:
			- run: echo "Deprecated workflow placeholder"