name: Markdown Lint

on:
  push:
    branches: [ main, develop ]
    paths:
      - '**.md'
  pull_request:
    branches: [ main ]
    paths:
      - '**.md'

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '22.17.1'

      - name: Install markdownlint-cli2
        run: npm install -g markdownlint-cli2

      - name: Run markdownlint
        run: markdownlint-cli2 "**/*.md" --config .markdownlint.json

      - name: Comment PR with results
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const output = `#### Markdown Lint Results ❌
            
            Markdown linting failed. Please fix the issues and push again.
            
            You can run the linter locally with:
            \`\`\`bash
            markdownlint-cli2 "**/*.md" --config .markdownlint.json
            \`\`\`
            
            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })