name: Auto-fix Markdown

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**.md'
  workflow_dispatch:

jobs:
  autofix-markdown:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '20.19.2'
          cache: 'npm'

      - name: Install markdownlint-cli2
        run: npm install -g markdownlint-cli2

      - name: Auto-fix markdown issues
        run: markdownlint-cli2 "**/*.md" --config .markdownlint.json --fix

      - name: Check for changes
        id: changes
        run: |
          if [[ -n $(git status -s) ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit auto-fixes
        if: steps.changes.outputs.changes == 'true'
        run: |
          git config --global user.name 'markdown-autofix[bot]'
          git config --global user.email 'markdown-autofix[bot]@users.noreply.github.com'
          git add .
          git commit -m "🔧 Auto-fix markdown formatting issues"
          git push

      - name: Comment on PR
        if: steps.changes.outputs.changes == 'true' && github.event_name == 'pull_request'
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const output = `#### 🔧 Markdown Auto-fix Applied
            
            Automatic markdown formatting fixes have been applied to this PR.
            
            The following issues were automatically resolved:
            - Line length violations
            - Missing blank lines around headings/lists
            - Code block formatting
            - Other style inconsistencies
            
            *Generated by markdown-autofix workflow*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })