name: Update Last Updated Badge

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'  # Prevents infinite loop of commits
  schedule:
    - cron: '0 0 * * 0'  # Runs at midnight every Sunday
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-timestamp:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed to push changes
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Update README timestamp
        run: |
          # Get current date in YYYY-MM-DD format
          CURRENT_DATE=$(date '+%Y-%m-%d')
          
          # Replace the date in the README badge
          python -c "
          import re
          
          # Read README content
          with open('README.md', 'r') as f:
              content = f.read()
          
          # Update the Last Updated badge with regex
          updated_content = re.sub(
              r'(!\[Last Updated\]\(https://img\.shields\.io/badge/Last%20Updated-)[0-9]{4}--[0-9]{2}--[0-9]{2}(-success\))',
              r'\g<1>${CURRENT_DATE}\g<2>',
              content
          )
          
          # Write updated content back to README
          with open('README.md', 'w') as f:
              f.write(updated_content)
          " | sed "s/\${CURRENT_DATE}/$CURRENT_DATE/g"
          
      - name: Commit and push changes
        run: |
          # Check if there are changes to commit
          if [[ -n $(git status -s) ]]; then
            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github-actions[bot]@users.noreply.github.com'
            git add README.md
            git commit -m "Update Last Updated badge to $(date '+%Y-%m-%d')"
            git push
          else
            echo "No changes to commit"
          fi